### PR TITLE
Some misc updates to eg/hello, Dockerfiles and top level Makefile

### PR DESCRIPTION
**Pull request by tcwan**
Hi,
I've been making some misc updates to the project to fix some issues with the build process. 

The most important change is the addition of a top level Makefile. I'm using Eclipse IDE and building subdirectories from the GUI interface is a bit tricky for novice users without a top level Makefile.
>You can see some work-in-progress documentation [here](https://github.com/tcwan/edu-docs/blob/master/docs/programming/eclipse-ide.md).

I've also updated the Dockerfiles to cater for stretch cross-compiler builds. Currently I'm working on porting ev3dev-c to stretch in my [fork](https://github.com/tcwan/ev3dev-c) but it's still too preliminary to merge.

Other than that, I've also fixed the Example Debug build configuration, as well as updated the eg/hello Makefile to use the same structure as the others.

By the way, there's some build issue with tacho_cpp which I've not tried to debug yet.

### CODE REVIEW

**Comment by tcwan** [comment]
I've made some further changes to the example Makefiles:
1. There is a circular dependency for the debug-clean rule.
2. The default action for make clean will delete the yupp-generated *.h and *.c files, I've modified it to only delete the object and binary files.
3. Added a clean-all target to perform a complete clean
4. I've replaced the Makefile for tacho_cpp with the default Makefile to solve build issues. This behaves slightly differently in that it will not link against the libev3dev-c.a library, but instead include the *.o statically. I'm not sure if you intended to test the library linking in the original makefile or not. 

I've also made some changes to the top level Makefiles in eg/.
1. The Makefiles will fail when the output directory does not exist. I've fixed that with a `mkdir -p` during the Linking phase
2. To link tacho_cpp correctly, I had to change the linker to g++. This seems to work properly for the other C-based examples, but the generated binary files have a different size compared to using gcc as the linker.
3. I've replaced Makefile.Release with Makefile.Debug (modifying D_BIN) appropriately, since the existing Makefile.Release does not take care of C++ source files.

**Comment by in4lio** [comment]
Hi -- I will look into it on next week. Thanks!

**Comment by tcwan** [comment]
There is a conflict between the compiler outputs for `tacho.cpp` and `tacho.c` since the object files are both named `tacho.o`. Depending on which was built last, the generated binary file will be incorrect for one of them. I think the best solution is to rename tacho.cpp to something else.

**Comment by tcwan** [comment]
I'm closing this pull request since there are multiple issues described here, some of which have been addressed in the 5d4ac70177bacab37d322d20b0bf90c4e0e088a1 commit.

**Pull request closed without merging**
